import os
from supabase import create_client
from dotenv import load_dotenv

load_dotenv('d:/Automator_Prj/Quantix_AI_Core/.env')

url = os.environ.get("SUPABASE_URL")
key = os.environ.get("SUPABASE_SERVICE_ROLE_KEY") or os.environ.get("SUPABASE_KEY")

supabase = create_client(url, key)

print("--- LAST 5 ANALYSIS LOGS ---")
try:
    response = supabase.table("fx_analysis_log").select("*").order("timestamp", desc=True).limit(5).execute()
    for row in response.data:
        print(f"[{row.get('timestamp')}] | {row.get('asset')} | {row.get('direction')} | Conf: {row.get('confidence')} | Path: {row.get('status')}")
except Exception as e:
    print(f"Error fetching logs: {e}")

print("\n--- LAST 3 SIGNALS ---")
try:
    # Look for Signals in PREPARED state (newly generated by v3.5)
    response = supabase.table("fx_signals").select("*").order("generated_at", desc=True).limit(3).execute()
    for row in response.data:
        print(f"[{row.get('generated_at')}] | ID: {row.get('id')} | {row.get('asset')} {row.get('direction')} | Conf: {row.get('release_confidence')} | Status: {row.get('status')}")
except Exception as e:
    print(f"Error fetching signals: {e}")
