
-- Run this in your Supabase SQL Editor to enable Cloud-Native AI Learning
CREATE TABLE IF NOT EXISTS fx_analysis_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp TIMESTAMPTZ NOT NULL,
    asset TEXT NOT NULL,
    price DOUBLE PRECISION NOT NULL,
    direction TEXT NOT NULL,
    confidence DOUBLE PRECISION NOT NULL,
    status TEXT NOT NULL
);

-- Index for performance analysis
CREATE INDEX IF NOT EXISTS idx_analysis_timestamp ON fx_analysis_log(timestamp);
